version: "3.5"

services:
  go-course-web:
    platform: linux/amd64
    container_name: gotest_app
    build:
      context: ./.dockers/postgres
      dockerfile: Dockerfile

    environment:
      POSTGRES_DB: gotest_db
      POSTGRES_USER: gotest_user
      POSTGRES_PASSWORD: gotest_pass
    ports:
      - "5440:5432"
    volumes:
      - ./.dockers/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
